INSERT INTO VEHICLE("ID", "PLATE", "TYPE") VALUES (1, 'AA-AA-00', 'CAR')
INSERT INTO VEHICLE("ID", "PLATE", "TYPE") VALUES (2, 'BB-BB-11', 'TRUCK')
INSERT INTO VEHICLE("ID", "PLATE", "TYPE") VALUES (3, 'CC-CC-22', 'BIKE')
